### ISSUE TITLE
While trying to upload a file it errors with falsy-positive "invalid yaml syntax"

### ISSUE THREAD

**Issue by Arkemlar** [vandetho/symflowbuilder#1]
1. Open the page:
<img width="600" alt="изображение" src="https://github.com/user-attachments/assets/86de0f61-1adc-4cb8-b886-b1263827702c">

2. Drag and drop file to site
3. See "The file is not a valid yaml file. Please try again." error popup.

File is a valid yaml file validated by `bin/console lint:yaml` symfony command.
<details><summary>File contents</summary>
<p>

```yaml
framework:
    workflows:
        purchase_order:
            metadata:
                transitions_enum: \App\Context\Purchase\Order\App\StateMachine\TransitionEnum
                places_enum: \App\Context\Purchase\Order\Domain\PurchaseOrderStatus
            type: 'state_machine'
            supports: \App\Context\Purchase\Order\Domain\PurchaseOrder
            audit_trail:
                enabled: true
            marking_store:
                property: 'statusString'
            initial_marking: created
            places:
                - created
                - logistics_preparation
                - in_transit
                - arrived_to_warehouse
                - goods_receiving
                - waiting_for_documents
                - goods_issue_solving
                - completed
                - archived
                - canceled
            transitions:
                accept_for_execution:
                    from: created
                    to:   logistics_preparation
                mark_in_transit:
                    from: logistics_preparation
                    to:   in_transit
                mark_arrived_to_warehouse:
                    from: in_transit
                    to:   arrived_to_warehouse
                start_goods_receiving:
                    from: arrived_to_warehouse
                    to:   goods_receiving
                finish_goods_receiving:
                    from: goods_receiving
                    to:   waiting_for_documents
                documents_attached:
                    from: goods_receiving
                    to:   goods_issue_solving
                complete:
                    from: goods_issue_solving
                    to:   completed
                archive:
                    from: completed
                    to:   archived
                cancel:
                    from: [created, logistics_preparation, in_transit]
                    to:   canceled

```

</p>
</details>
